ECTable.Admin/ViewModels/ManagerViewModels.cs
using ECTable.Admin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using PagedList;

namespace ECTable.Admin.ViewModels
{
    public class ManagerViewModel
    {
        /// <summary>
        /// 是否能新增帳號
        /// </summary>
        public string IsAdd { get; set; }

        /// <summary>
        /// 目前頁數
        /// </summary>
        public int PageNo { get; set; }

        /// <summary>
        /// 每頁大小
        /// </summary>
        public int PageSize { get; set; }

        /// <summary>
        /// 目前頁內容
        /// </summary>
        public IPagedList<ManagerItem> QueryList { get; set; }

        /// <summary>
        /// 目前排序欄位
        /// </summary>
        public ManagerSortingField SortingField { get; set; }

        /// 目前排序方向
        /// </summary>
        public SortingDirection SortingDirection { get; set; }

        public ManagerViewModel()
        {
            this.PageNo = 1;
            this.PageSize = int.Parse(System.Web.Configuration.WebConfigurationManager.AppSettings["PageSize"]);
            this.SortingField = ManagerSortingField.None;
            this.SortingDirection = SortingDirection.None;
        }
    }

    /// <summary>
    /// 帳號管理 - Item
    /// </summary>
    public class ManagerItem
    {
        /// <summary>
        /// 編號
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// 帳號
        /// </summary>
        public string UID { get; set; }

        /// <summary>
        /// 最後登入IP
        /// </summary>
        public string Login_IpAddress { get; set; }

        /// <summary>
        /// 最後登入日期
        /// </summary>
        public string LoginTime { get; set; }

        /// <summary>
        /// 狀態0代表停用1代表正常
        /// </summary>
        public sbyte  Status { get; set; }        
    }

    /// <summary>
    /// 帳號管理 - EditViewModel
    /// </summary>
    public class ManagerEditViewModel
    {
        /// <summary>
        /// 編號
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// 帳號
        /// </summary>
        public string UID { get; set; }
        /// <summary>
        /// 密碼
        /// </summary>
        public string Pwd { get; set; }

        /// <summary>
        /// 狀態0代表停用1代表正常
        /// </summary>
        public sbyte Status { get; set; }

        /// <summary>
        /// 超級管理員0代表停用1代表正常
        /// </summary>
        public sbyte IsUserPower { get; set; }

        /// <summary>
        /// 新增時間 - 顯示用
        /// </summary>
        public string CreateTime { get; set; }

        /// <summary>
        /// 編輯時間 - 顯示用
        /// </summary>
        public string UpdateTime { get; set; }
    }
}

ECTable.Admin/Controllers/ManagerController.cs
using NLog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ECTable.Admin.ViewModels;
using ECTable.Admin.Models;
using System.ComponentModel;
using ECTable.DataSource;
using MySql.Data.MySqlClient;
using ECTable.Utils;
using System.Data;
using PagedList;
using Filters;

namespace ECTable.Admin.Controllers
{
    /// <summary>
    /// 帳號管理
    /// </summary>
    [SiteAuthorize()]
    public class ManagerController : Controller
    {
        private static DBUtility db = new DBUtility(DBUtility.DBServer.DB); // 資料庫連線
        protected static Logger _logger = LogManager.GetCurrentClassLogger(); // NLog 宣告
        
        /// <summary>
        /// 帳號管理 - 列表
        /// </summary>
        /// <param name="pageNo">目前頁數</param>
        /// <returns></returns>
        public ActionResult ManagerList(ManagerViewModel viewModel, [DefaultValue(1)]int pageNo,
            ManagerSortingField sortingField = ManagerSortingField.None, SortingDirection sortingDirection = SortingDirection.None)
        {
            try
            {
                int n = 0;
                if (Convert.ToInt32(Session["IsUserPower"]) != 1)
                {
                    n = 1;
                }

                MySqlParameter[] para = new MySqlParameter[n];
                //// 取出資料            
                string sql = "select id,uid,Login_IpAddress,case when LoginTime is null then '未登入' else LoginTime end LoginTime,status from manager where status<>2 " + Environment.NewLine;
                string isAdd = "style='display:block;'";
                if (Convert.ToInt32(Session["IsUserPower"]) != 1)
                {
                    isAdd = "style=display:none;";
                    sql += " where Uid=@Uid";
                    para[0] = new MySqlParameter("Uid", Session["Uid"].ToString());
                }
                viewModel.IsAdd = isAdd;
                DataTable dt = db.FillDataTable(CommandType.Text, sql, para);

                if (dt != null && dt.Rows.Count > 0)
                {
                    IQueryable<ManagerItem> queryList = (from a in dt.AsEnumerable()
                                                         select new ManagerItem()
                                                         {
                                                             Id = a["Id"].ToString(),
                                                             UID = a["Uid"].ToString(),
                                                             Status = Convert.ToSByte(a["Status"].ToString()),
                                                             Login_IpAddress = a["Login_IpAddress"].ToString(),
                                                             LoginTime = a["LoginTime"].ToString()
                                                         }).AsQueryable();

                    #region 排序處理
                    switch (viewModel.SortingField)
                    {
                        case ManagerSortingField.Uid:
                            if (viewModel.SortingDirection == SortingDirection.Desc)
                                queryList = queryList.OrderByDescending(t => t.UID);
                            else
                                queryList = queryList.OrderBy(t => t.UID);
                            break;
                        case ManagerSortingField.LoginIpAddress:
                            if (viewModel.SortingDirection == SortingDirection.Desc)
                                queryList = queryList.OrderByDescending(t => t.Login_IpAddress);
                            else
                                queryList = queryList.OrderBy(t => t.Login_IpAddress);
                            break;
                        case ManagerSortingField.LoginTime:
                            if (viewModel.SortingDirection == SortingDirection.Desc)
                                queryList = queryList.OrderByDescending(t => t.LoginTime);
                            else
                                queryList = queryList.OrderBy(t => t.LoginTime);
                            break;
                        case ManagerSortingField.Status:
                            if (viewModel.SortingDirection == SortingDirection.Desc)
                                queryList = queryList.OrderByDescending(t => t.Status);
                            else
                                queryList = queryList.OrderBy(t => t.Status);
                            break;
                        default:
                            viewModel.SortingField = ManagerSortingField.None;
                            viewModel.SortingDirection = SortingDirection.None;
                            break;
                    }
                    #endregion

                    // 分頁
                    viewModel.PageNo = pageNo;
                    viewModel.QueryList = queryList.ToPagedList(viewModel.PageNo, viewModel.PageSize);
                }
            }
            catch (Exception ex)
            {
                ViewData["Message"] = String.Format("發生錯誤：{0}", ex.Message);
                _logger.Error(String.Format("登入管理 - 列表，發生錯誤：{0}", ex));
            }

            return View(viewModel);
        }

        /// <summary>
        /// 帳號管理 - 新增 - get
        /// </summary>
        /// <returns></returns>
        public ActionResult AddManager()
        {
            ManagerEditViewModel viewModel = new ManagerEditViewModel();
            
            try
            {
                if (Convert.ToInt32(Session["IsUserPower"]) != 1)
                {
                    ViewData["Message"] = "你的帳號沒有權限新增";
                }

                viewModel.Status = 1;
                viewModel.IsUserPower = 0;
                viewModel.CreateTime = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss");
            }
            catch (Exception ex)
            {
                ViewData["Message"] = String.Format("發生錯誤：{0}", ex.Message);
                _logger.Error(String.Format("帳號管理 - 新增 - get，發生錯誤：{0}", ex));
            }

            return View(viewModel);
        }

        /// <summary>
        /// 帳號管理 - 新增 - post
        /// </summary>
        /// <param name="viewModel">ManagerEditViewModel</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult AddManager(ManagerEditViewModel viewModel)
        {
            try
            {
                int id = GetMaxID();
                DateTime createTime = Convert.ToDateTime(viewModel.CreateTime);
                MySqlParameter[] para = new MySqlParameter[7];
                string sql = "insert into manager(id,Uid,Login_Password,IsUserPower,Status,CreateID,CreateTime)values(@id,@Uid,@Login_Password,@IsUserPower,@Status,@CreateID,@CreateTime)";
                string pwd = Utils.Security.SecurityPlus.encryptMd5(viewModel.Pwd + createTime.ToString("yyyy-MM-ddTHH:mm:ss"));

                para[0] = new MySqlParameter("CreateID", Session["Uid"].ToString());
                para[1] = new MySqlParameter("Uid", viewModel.UID);
                para[2] = new MySqlParameter("Login_Password", pwd);
                para[3] = new MySqlParameter("IsUserPower", viewModel.IsUserPower);
                para[4] = new MySqlParameter("Status", viewModel.Status);
                para[5] = new MySqlParameter("CreateTime", createTime);
                para[6] = new MySqlParameter("id", id);

                int act = db.ExecuteNonQuery(CommandType.Text, sql, para);
                if (act == 0)
                {
                    ViewData["Message"] = "新增失敗！";
                }
                else
                {
                    ViewData["Message"] = "新增成功！";
                }
            }
            catch (Exception ex)
            {
                ViewData["Message"] = String.Format("新增失敗，發生錯誤：{0}", ex.Message);
                _logger.Error(String.Format("帳號管理 - 新增 - post，發生錯誤：{0}", ex));
            }

            return View(viewModel);
        }

        /// <summary>
        /// 取得 manager 的最新的 id
        /// </summary>
        /// <returns>MaxID</returns>
        public int GetMaxID()
        {
            int intValue = 0;
            string strValue = "0";

            try
            {
                string sql = "select max(id)+1 from manager";
                strValue = StringTool.IIfCheckDBNull(db.ExecuteScalar(CommandType.Text, sql, null)).ToString();
                if (strValue == "") strValue = "1";
                intValue = int.Parse(strValue);
            }
            catch (Exception ex)
            {
                _logger.Error(String.Format("取得 manager 的最新的 id，發生錯誤：{0}", ex));
            }

            return intValue;
        }

        /// <summary>
        /// 驗證帳號
        /// </summary>
        /// <param name="uid">帳號編號</param>
        /// <param name="pageNo">目前頁數</param>
        /// <param name="pageSize">分頁大小</param>
        /// <returns></returns>
        [HttpPost]
        public int CheckManagerUid([DefaultValue("")]string uid, [DefaultValue(1)]int pageNo, [DefaultValue(10)]int pageSize)
        {
            try
            {
                MySqlParameter[] para = new MySqlParameter[1];
                string sql = "select uid from manager where Uid=@Uid" + Environment.NewLine;
                para[0] = new MySqlParameter("Uid", uid);
                DataTable dt = db.FillDataTable(CommandType.Text, sql, para);

                if (dt != null && dt.Rows.Count > 0)
                {
                    return 1;
                }
                else
                {
                    return 0;
                }
            }
            catch (Exception ex)
            {
                _logger.Error(String.Format("驗證帳號，發生錯誤：{0}", ex));
                return 0;
            }
        }

        /// <summary>
        /// 帳號管理 - 編輯 - get
        /// </summary>
        /// <param name="uid">帳號編號</param>

ECTable.Admin/Views/Manager/AddManager.cshtml
@model ECTable.Admin.ViewModels.ManagerEditViewModel
@{
    ViewBag.Title = "AddManager";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section scripts{
    <script type="text/javascript">
        $(function () {
            @if(ViewData["Message"] != null)
            {
                if (ViewData["Message"].ToString().IndexOf("成功") != -1)
                {
                    <text>
                    alert('@ViewData["Message"].ToString()');
                    document.location.href = '@Url.Action("ManagerList")';
                    </text>
                }
                else if (ViewData["Message"].ToString().IndexOf("你的帳號沒有權限新增") != -1)
                {
                    <text>
                    alert('@ViewData["Message"].ToString()');
                    document.location.href = '@Url.Action("ManagerList")';
                    </text>
                }
                else
                {
                    {
                    <text>
                        alert('@ViewData["Message"].ToString()');
                    </text>
                }
                }
            }
        });

        function getSubmit() {
            var uid = $("#Uid");
            var pwd = $("#Pwd");
            var chkPwd = $("#ChkPwd");
            var error = "";
            if (uid.val() == '') {
                error += '帳號 不能為空白\n';
            }
            else {
                if (IsStr(uid.val()) == false) {
                    error += '帳號 只能輸入英數字\n';
                }
                else {
                    if (uid.val().length <= 3) {
                        error += '帳號 至少要4個字元\n';
                    }
                    else {
                        $.ajax({
                            url: '@Url.Action("CheckManagerUid", "Manager")',
                            type: 'POST',
                            data: { Uid: uid.val() },
                            success: function (data) {
                                //資料更新完重整選單
                                if (data == 1) {
                                    alert('已有此帳號，請重新輸入');
                                }
                            },
                            error: function (XMLHttpRequest, textStatus, errorThrown) {
                                alert('系統維護中');
                            }
                        })
                    }
                }
            }
            if (pwd.val() == '') {
                error += '密碼 不能為空白\n';
            }
            else {
                if (IsStr(pwd.val()) == false) {
                    error += '密碼 只能輸入英數字\n';
                }
                else {
                    if (pwd.val().length <= 5) {
                        error += '密碼 至少要6個字元\n';
                    }
                }
            }
            if (pwd.val() != chkPwd.val()) {
                error += '密碼與確認密碼不同\n';
            }
            if (error != '') {
                alert(error);
                return false;
            } else {
                $("#AddForm").submit();
            }
        }
        function IsStr(v) {
            var vArr = v.match(/^[A-Za-z0-9]+$/);
            if (vArr == null) {
                return false;
            } else {
                return true;
            }
        }
    </script>
}

<section class="MainContent">
    <div class="BreadcrumbTrail"><img src="@Url.Content("~/img/LiPic.png")" width="6" height="9" alt="" /> 首頁 / 帳號管理</div>
    <h1>.:: 帳號管理</h1>
    <article class="Padding2">
        <h2>Step.1 新增帳號設定</h2>
        @using (Html.BeginForm("AddManager", null, null, FormMethod.Post, new { @id = "AddForm", @class = "form-horizontal" }))
        {
            @Html.HiddenFor(x => x.Id)

            <table width="100%" border="0" cellspacing="0" cellpadding="0" id="ProductWay" class="STable">
                <tr>
                    <th><label for="CreateTime">新增時間</label></th>
                    <td><input name="CreateTime" type="text" class="Form100" id="CreateTime" value="@Model.CreateTime" required disabled /></td>
                </tr>
                <tr>
                    <th><label for="Uid">帳號</label></th>
                    <td><input name="Uid" type="text" required class="Form100" id="Uid" value="@Model.UID" size="100" maxlength="32" /></td>
                </tr>
                <tr>
                    <th><label for="Status">狀態</label></th>
                    <td>
                        <label>
                            <input type="radio" name="Status" value="1" id="Status1" @if (Model.Status == 1) { <text> checked="checked" </text>     }>啟用
                        </label>
                        <label>
                            <input type="radio" name="Status" value="0" id="Status2" @if (Model.Status == 0) { <text> checked="checked" </text>      }>停用
                        </label>
                    </td>
                </tr>
                <tr>
                    <th><label for="IsUserPower">超級管理員</label></th>
                    <td>
                        <label>
                            <input type="radio" name="IsUserPower" value="1" id="IsUserPower1" @if (Model.IsUserPower == 1) { <text> checked="checked" </text>        }>是
                        </label>
                        <label>
                            <input type="radio" name="IsUserPower" value="0" id="IsUserPower2" @if (Model.IsUserPower == 0) { <text> checked="checked" </text>          }>否
                        </label>
                    </td>
                </tr>
                <tr>
                    <th><label for="Pwd">密碼</label></th>
                    <td>
                        <input name="Pwd" type="password" required class="Form100" id="Pwd" size="100" maxlength="20" />
                    </td>
                </tr>
                <tr>
                    <th><label for="ChkPwd">確認密碼</label></th>
                    <td>
                        <input name="ChkPwd" type="password" required class="Form100" id="ChkPwd" size="100" maxlength="20" />
                    </td>
                </tr>
            </table>

            <input name="Submit" type="button" class="submitBtm" id="SendButton" value="送出" onclick="getSubmit()" />
        }
    </article>
</section>

ECTable.Admin/Views/Manager/EditManager.cshtml
@model ECTable.Admin.ViewModels.ManagerEditViewModel
@{
    ViewBag.Title = "EditManager";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section scripts{
    <script type="text/javascript">
        $(function () {
            @if(ViewData["Message"] != null)
            {
                if (ViewData["Message"].ToString().IndexOf("成功") != -1)
                {
                    <text>
                    alert('@ViewData["Message"].ToString()');
                    document.location.href = '@Url.Action("ManagerList")';
                    </text>
                }
                else if (ViewData["Message"].ToString().IndexOf("沒有權限") != -1 || ViewData["Message"].ToString().IndexOf("無此帳號") != -1)
                {
                    <text>
                    alert('@ViewData["Message"].ToString()');
                    document.location.href = '@Url.Action("ManagerList")';
                    </text>
                }
                else
                {
                    <text>
                        alert('@ViewData["Message"].ToString()');document.location.href = '@Url.Action("ManagerList", 
                        new {
                            pageNo = ViewData["PageNo"].ToString(),
                            pageSize = ViewData["PageSize"].ToString()
                        })';
                    </text>
                }
            }
        });

        function getSubmit() {            
            var pwd = $("#Pwd");
            var chkPwd = $("#ChkPwd");
            var error = "";
            if (pwd.val() != '') {                            
                if (IsStr(pwd.val()) == false) {
                    error += '密碼 只能輸入英數字\n';
                }
                else {
                    if (pwd.val().length <= 5) {
                        error += '密碼 至少要6個字元\n';
                    }
                }
                if (pwd.val() != chkPwd.val()) {
                    error += '密碼與確認密碼不同\n';
                }
            }
            if (error != '') {
                alert(error);
                return false;
            } else {
                $("#EditForm").submit();
            }
        }
        function IsStr(v) {
            var vArr = v.match(/^[A-Za-z0-9]+$/);
            if (vArr == null) {
                return false;
            } else {
                return true;
            }
        }
    </script>
}

<section class="MainContent">
    <div class="BreadcrumbTrail"><img src="@Url.Content("~/img/LiPic.png")" width="6" height="9" alt="" /> 首頁 / 帳號管理</div>
    <h1>.:: 帳號管理</h1>
    <article class="Padding2">
        <h2>Step.1 編輯帳號設定</h2>
        @using (Html.BeginForm("EditManager", null, null, FormMethod.Post, new { @id = "EditForm", @class = "form-horizontal" }))
        {
            @Html.HiddenFor(x => x.Id)
            @Html.HiddenFor(x => x.CreateTime)
            @Html.Hidden("PageNo", ViewData["PageNo"])
            @Html.Hidden("PageSize", ViewData["PageSize"])
            <table width="100%" border="0" cellspacing="0" cellpadding="0" id="ProductWay" class="STable">
                <tr>
                    <th><label for="UpdateTime">編輯時間</label></th>
                    <td><input name="UpdateTime" type="text" class="Form100" id="createTime" value="@Model.UpdateTime" required disabled /></td>
                </tr>
                <tr>
                    <th><label for="Uid">帳號</label></th>
                    <td><input name="Uid" type="text" required class="Form100" id="Uid" value="@Model.UID" disabled size="100" maxlength="32" /></td>
                </tr>
                @if (Convert.ToSByte(Session["IsUserPower"].ToString()) == 1)
                { 
                <tr>
                    <th><label for="Status">狀態</label></th>
                    <td>
                        <label>
                            <input type="radio" name="Status" value="1" id="Status1" @if (Model.Status == 1) { <text> checked="checked" </text>      }>啟用
                        </label>
                        <label>
                            <input type="radio" name="Status" value="0" id="Status2" @if (Model.Status == 0) { <text> checked="checked" </text>        }>停用
                        </label>
                    </td>
                </tr>
                <tr>
                    <th><label for="Status">超級管理員</label></th>
                    <td>
                        <label>
                            <input type="radio" name="IsUserPower" value="1" id="IsUserPower1" @if (Model.IsUserPower == 1) { <text> checked="checked" </text>        }>是
                        </label>
                        <label>
                            <input type="radio" name="IsUserPower" value="0" id="IsUserPower2" @if (Model.IsUserPower == 0) { <text> checked="checked" </text>           }>否
                        </label>
                    </td>
                </tr>
                }
                <tr>
                    <th><label for="Pwd">密碼</label></th>
                    <td>
                        <input name="Pwd" type="password" required class="Form100" id="Pwd" size="100" maxlength="20" />
                        <br /><font color="red">如需要更改密碼，請填寫密碼</font>
                    </td>
                </tr>
                <tr>
                    <th><label for="ChkPwd">確認密碼</label></th>
                    <td>
                        <input name="ChkPwd" type="password" required class="Form100" id="ChkPwd" size="100" maxlength="20" />
                    </td>
                </tr>
            </table>

            <input name="Submit" type="button" class="submitBtm" id="SendButton" value="送出" onclick="getSubmit()" />
        }
    </article>
</section>

ECTable.Admin/Views/Manager/ManagerList.cshtml
@model ECTable.Admin.ViewModels.ManagerViewModel
@{
    ViewBag.Title = "ManagerList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts{
    <script type="text/javascript">
    $(function () {
        @if(ViewData["Message"] != null)
        {
            <text>
                alert('@ViewData["Message"].ToString()');
            </text>
        }
    });

    function deleteSubmit(id) {
        if (confirm("你確定要刪除此筆資料?") == true) {
            $.ajax({
                url: '@Url.Action("EditManager", "Manager")',
                    type: 'POST',
                    data: { Id: id, Status: 2 },
                    success: function (data) {
                        if (data == 1) {
                            alert('資料刪除成功');
                        }
                        else {
                            alert('資料刪除失敗，請連絡it人員');
                        }
                        $('#ListForm').submit();
                    },
                    error: function (XMLHttpRequest, textStatus, errorThrown) {
                        alert('系統維護中');
                    }
                })
            }
        }

        //狀態變更
        function StatusScript(id, Status) {
            var Msg = "";
            if (Status == 1) {
                Msg = "你確定要把狀態變更為啟用?"
            }
            else {
                Msg = "你確定要把狀態變更為停用?"
            }
            if (confirm(Msg) == true) {
                $.ajax({
                    url: '@Url.Action("EditManagerStatus", "Manager")',
                    type: 'POST',
                    data: { id: id, Status: Status },
                    success: function (data) {
                        //資料更新完重整選單
                        if (data == 1) {
                            alert('狀態變更成功');
                        }
                        else {
                            alert('狀態變更失敗，請連絡it人員');
                        }
                        $('#ListForm').submit();
                    },
                    error: function (XMLHttpRequest, textStatus, errorThrown) {
                        alert('系統維護中');
                    }
                })
            }
        }
    </script>
}

<section class="MainContent">
    <div class="BreadcrumbTrail"><img src="@Url.Content("~/img/LiPic.png")" width="6" height="9" alt="" /> 首頁 / 帳號管理</div>
    <h1>.:: 帳號管理</h1>
    <article class="Padding2">
        @using (Html.BeginForm("ManagerList", null, null, FormMethod.Get, new { @id = "ListForm" }))
        {
            <div class="AddBtm" @Model.IsAdd><a href="@Url.Action("AddManager")">新增帳號</a></div>

            @Html.Partial("_SortingPartial")
            @Html.Hidden("PageNo", Model.PageNo)
            
            if (Model.QueryList != null)
            {
                <div id="SmallBuildNav">
                    @Html.PagedListPager(Model.QueryList, Page => Url.Action("ManagerList",
                 new { pageNo = Page, SortingField = Model.SortingField, SortingDirection = Model.SortingDirection }), SiteLibrary.GetDefaultPagerOptions())
                </div>
            }

            <table width="100%" border="0" cellspacing="0" cellpadding="0" id="ProductList" class="HTable">

                @if (Model.QueryList == null || Model.QueryList.Count == 0)
                {
                    <tr>
                        <td colspan="6" align="center"><span class="notice">查無資料!!</span></td>
                    </tr>
                }
                else
                {
                    <tr>
                        <th width="20%">@Html.SortingColumnCust("帳號", ManagerSortingField.Uid, Model.SortingField, Model.SortingDirection)</th>
                        <th width="10%">@Html.SortingColumnCust("狀態", ManagerSortingField.LoginIpAddress, Model.SortingField, Model.SortingDirection)</th>
                        <th width="20%">@Html.SortingColumnCust("最後登入IP", ManagerSortingField.LoginTime, Model.SortingField, Model.SortingDirection)</th>
                        <th width="26%">@Html.SortingColumnCust("最後登入時間", ManagerSortingField.Status, Model.SortingField, Model.SortingDirection)</th>
                        <th width="8%">編輯</th>
                        <th width="8%">刪除</th>
                    </tr>
                    <tbody id="TableNo">
                        @foreach (var data in Model.QueryList)
                        {
                            <tr>
                                <td>@data.UID</td>
                                <td>
                                    @if (data.Status == 1)
                                    {
                                        <text>
                                            @*<a href="javascript:void(0)" onclick="StatusScript(@data.Id,0)"><font color="blue">啟用</font></a>*@
                                            <font color="blue">啟用</font>
                                        </text>
                                    }
                                    else
                                    {
                                        <text>
                                            @*<a href="javascript:void(0)" onclick="StatusScript(@data.Id,1)"><font color="red">停用</font></a>*@
                                            <font color="red">停用</font>
                                        </text>
                                    }
                                </td>
                                <td>@data.Login_IpAddress</td>
                                <td>@data.LoginTime </td>                                
                                <td><a href="@Url.Action("EditManager", new { UID = data.UID, PageNo = Model.PageNo, PageSize = Model.PageSize })"><img src="@Url.Content("~/img/bedit.gif")" alt="edit" width="16" height="16" border="0" /></a></td>
                                <td><a href="javascript:void(0)" onclick="deleteSubmit(@data.Id)"><img src="@Url.Content("~/img/delete.gif")" alt="edit" width="16" height="16" border="0" /></a></td>
                            </tr>
                        }
                    </tbody>
                }
            </table>

            if (Model.QueryList != null)
            {
                <div id="SmallBuildNav">
                    @Html.PagedListPager(Model.QueryList, Page => Url.Action("ManagerList",
                 new { pageNo = Page, SortingField = Model.SortingField, SortingDirection = Model.SortingDirection }), SiteLibrary.GetDefaultPagerOptions())
                </div>
            }
        }
    </article>
</section>