ECTable.Admin/Controllers/BrandController.cs
using NLog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ECTable.Admin.ViewModels;
using ECTable.Admin.Models;
using System.ComponentModel;
using ECTable.DataSource;
using MySql.Data.MySqlClient;
using ECTable.Utils;
using System.Data;
using PagedList;
using Filters;
using ECTable.Utils.UploadFiles;

namespace ECTable.Admin.Controllers
{
    /// <summary>
    /// 品牌管理
    /// </summary>
    [SiteAuthorize()]
    public class BrandController : Controller
    {
        private static DBUtility db = new DBUtility(DBUtility.DBServer.DB); // 資料庫連線
        protected static Logger _logger = LogManager.GetCurrentClassLogger(); // NLog 宣告
        /// <summary>
        /// 品牌清單
        /// </summary>
        /// <returns></returns>
        public ActionResult BrandList(BrandViewModel viewModel, [DefaultValue(1)]int pageNo,
          [DefaultValue("")]string queryTitle, [DefaultValue(-1)]int queryStatus,
          BrandSortingField sortingField = BrandSortingField.None, SortingDirection sortingDirection = SortingDirection.None)
        {
            try
            {
                int n = 0;
                if (queryTitle != "")
                {
                    n += 1;
                }
                if (queryStatus != -1)
                {
                    n += 1;
                }
                //// 取出資料
                MySqlParameter[] para = new MySqlParameter[n];
                //string sql = "select c.Id, c.Title,c.Status,c.Sort,c.UpdateTime " + Environment.NewLine;
                //sql += ",ifnull((select count(distinct p.id) as Total from products p where p.status<>2 and brand_id=c.id group by p.class_id),0) as Quantity " + Environment.NewLine;
                //sql += "from products_brand c where c.status<>2 " + Environment.NewLine;
                string sql = "select c.Id, c.Title,c.Status,c.Sort,c.UpdateTime " + Environment.NewLine;
                sql += ",ifnull((select count(distinct p.id) as Total from products p where p.status<>2 and brand_id=c.id group by p.brand_id),0) as Quantity " + Environment.NewLine;
                sql += "from products_brand c where c.status<>2 " + Environment.NewLine;
                n = 0;
                if (queryTitle != "")
                {
                    sql += " and c.Title like Concat('%' ,@Title,'%')" + Environment.NewLine;
                    para[n] = new MySqlParameter("Title", queryTitle);
                    n += 1;
                }
                if (queryStatus != -1)
                {
                    sql += " and c.Status=@Status" + Environment.NewLine;
                    para[n] = new MySqlParameter("Status", queryStatus);
                }
                sql += " order by c.updatetime desc, c.createtime desc" + Environment.NewLine;
                DataTable dt = db.FillDataTable(CommandType.Text, sql, para);

                if (dt != null && dt.Rows.Count > 0)
                {
                    IQueryable<BrandItem> queryList = (from a in dt.AsEnumerable()
                                                       select new BrandItem()
                                                       {
                                                           Id = Convert.ToInt32(a["Id"].ToString()),
                                                           Title = a["Title"].ToString(),
                                                           Status = Convert.ToSByte(a["Status"].ToString()),
                                                           Sort = Convert.ToInt32(a["Sort"].ToString()),
                                                           Quantity = Convert.ToInt32(a["Quantity"].ToString()),
                                                           UpdateTime = DateTime.Parse(a["UpdateTime"].ToString()).ToString("yyyy-MM-dd")
                                                       }).AsQueryable();

                    #region 排序處理
                    switch (viewModel.SortingField)
                    {
                        case BrandSortingField.Id:
                            if (viewModel.SortingDirection == SortingDirection.Desc)
                                queryList = queryList.OrderByDescending(t => t.Id);
                            else
                                queryList = queryList.OrderBy(t => t.Id);
                            break;
                        case BrandSortingField.Title:
                            if (viewModel.SortingDirection == SortingDirection.Desc)
                                queryList = queryList.OrderByDescending(t => t.Title);
                            else
                                queryList = queryList.OrderBy(t => t.Title);
                            break;
                        case BrandSortingField.Quantity:
                            if (viewModel.SortingDirection == SortingDirection.Desc)
                                queryList = queryList.OrderByDescending(t => t.Quantity);
                            else
                                queryList = queryList.OrderBy(t => t.Quantity);
                            break;
                        case BrandSortingField.Status:
                            if (viewModel.SortingDirection == SortingDirection.Desc)
                                queryList = queryList.OrderByDescending(t => t.Status);
                            else
                                queryList = queryList.OrderBy(t => t.Status);
                            break;
                        case BrandSortingField.Sort:
                            if (viewModel.SortingDirection == SortingDirection.Desc)
                                queryList = queryList.OrderByDescending(t => t.Sort);
                            else
                                queryList = queryList.OrderBy(t => t.Sort);
                            break;
                        case BrandSortingField.UpdateTime:
                            if (viewModel.SortingDirection == SortingDirection.Desc)
                                queryList = queryList.OrderByDescending(t => t.Sort);
                            else
                                queryList = queryList.OrderBy(t => t.Sort);
                            break;
                        default:
                            viewModel.SortingField = BrandSortingField.None;
                            viewModel.SortingDirection = SortingDirection.None;
                            break;
                    }
                    #endregion

                    // 分頁
                    viewModel.PageNo = pageNo;
                    viewModel.QueryList = queryList.ToPagedList(viewModel.PageNo, viewModel.PageSize);
                }
            }
            catch (Exception ex)
            {
                ViewData["Message"] = String.Format("發生錯誤：{0}", ex.Message);
                _logger.Error(String.Format("品牌清單，發生錯誤：{0}", ex));
            }

            return View(viewModel);
        }


        /// <summary>
        /// 品牌管理 - 新增 - get
        /// </summary>
        /// <returns></returns>
        public ActionResult AddBrand()
        {
            BrandEditViewModel viewModel = new BrandEditViewModel();

            int fileSizeLimit = int.Parse(System.Web.Configuration.WebConfigurationManager.AppSettings["UploadFileSizeLimit"]);
            viewModel.FileSizeLimit = fileSizeLimit.ToString();
            
            try
            {
                viewModel.CreateTime = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss");
                viewModel.Status = 1;
            }
            catch (Exception ex)
            {
                ViewData["Message"] = String.Format("發生錯誤：{0}", ex.Message);
                _logger.Error(String.Format("品牌管理 - 新增 - get，發生錯誤：{0}", ex));
            }

            return View(viewModel);
        }

        /// <summary>
        /// 品牌管理 - 新增 - post
        /// </summary>
        /// <param name="viewModel">BrandEditViewModel</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult AddBrand(BrandEditViewModel viewModel)
        {
            string filePath = System.Web.Configuration.WebConfigurationManager.AppSettings["UploadFilePath"] + "/Brand/";
            string fileExtension = System.Web.Configuration.WebConfigurationManager.AppSettings["UploadFileExtension"];
            int fileSizeLimit = int.Parse(System.Web.Configuration.WebConfigurationManager.AppSettings["UploadFileSizeLimit"]);
            string img_path;
            string img_name;

            viewModel.FileSizeLimit = fileSizeLimit.ToString();

            try
            {
                //檔案判斷
                string FileErrMsg = FileTool.chkOneFiles(viewModel.uploadFiles, fileExtension, fileSizeLimit);

                if (FileErrMsg == null)
                {
                    //上傳檔案
                    Utils.Models.FilesModels filesModels = new Utils.Models.FilesModels();
                    filesModels = FileTool.uploadOneFile(viewModel.uploadFiles, Server.MapPath(filePath), filePath);
                    img_name = filesModels.FileName;
                    img_path = filesModels.FilePath;
                    MySqlParameter[] para = new MySqlParameter[10];
                    para[0] = new MySqlParameter("title", viewModel.Title);
                    para[1] = new MySqlParameter("img_path", img_path);
                    para[2] = new MySqlParameter("img_name", img_name);
                    para[3] = new MySqlParameter("status", viewModel.Status);
                    para[4] = new MySqlParameter("sort", viewModel.Sort);
                    para[5] = new MySqlParameter("seokeyword", viewModel.SeoKeyword);
                    para[6] = new MySqlParameter("seodesc", viewModel.SeoDesc);
                    para[7] = new MySqlParameter("content", viewModel.Content);
                    para[8] = new MySqlParameter("createid", Session["Uid"].ToString());

ECTable.Admin/Controllers/CurationController.cs
using Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ECTable.Admin.Controllers
{
    /// <summary>
    /// 策展管理
    /// </summary>
    [SiteAuthorize()]
    public class CurationController : Controller
    {
        /// <summary>
        /// 策展清單
        /// </summary>
        /// <returns></returns>
        public ActionResult CurationList()
        {
            return View();
        }

        /// <summary>
        /// 策展管理 - 新增
        /// </summary>
        /// <returns></returns>
        public ActionResult AddCuration()
        {
            return View();
        }

        /// <summary>
        /// 策展管理 - 編輯
        /// </summary>
        /// <returns></returns>
        public ActionResult EditCuration()
        {
            return View();
        }

        /// <summary>
        /// 策展管理 - 刪除
        /// </summary>
        /// <returns></returns>
        public ActionResult DeleteCuration()
        {
            return RedirectToAction("CurationList");
        }
	}
}

ECTable.Admin/Controllers/ProgramController.cs
using Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ECTable.Admin.Controllers
{
    /// <summary>
    /// 訂閱計畫管理
    /// </summary>
    [SiteAuthorize()]
    public class ProgramController : Controller
    {
        /// <summary>
        /// 訂閱計畫清單
        /// </summary>
        /// <returns></returns>
        public ActionResult ProgramList()
        {
            return View();
        }

        /// <summary>
        /// 訂閱計畫管理 - 新增
        /// </summary>
        /// <returns></returns>
        public ActionResult AddProgram()
        {
            return View();
        }

        /// <summary>
        /// 訂閱計畫管理 - 編輯
        /// </summary>
        /// <returns></returns>
        public ActionResult EditProgram()
        {
            return View();
        }
	}
}

ECTable.Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta http-equiv="content-language" content="zh-tw">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=0">
    <title>永齡鮮生夏小姐管理後台@*@ViewBag.Title*@</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <link rel="icon" href="@Url.Content("~/img/logo.ico")" type="image/x-icon" />

    @*@Styles.Render("~/css/css")*@
    @*@Scripts.Render("~/bundles/modernizr")*@

    <!-- CSS -->
    <link href="@Url.Content("~/css/css.css")" rel="stylesheet" type="text/css"><!--主版樣式-->
    <link href="@Url.Content("~/Content/PagedList.css")" rel="stylesheet" /><!--分頁樣式-->

    <!-- JQuery -->
    <script src="@Url.Content("~/js/jquery-1.10.2.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/js/commonjs.js")" type="text/javascript"></script><!--共用腳本-->

    <script type="text/javascript">

    </script>

    @RenderSection("scripts", required: false)
</head>
<body>
    <!-- Menu Start -->
    @Html.Partial("_MenuPartial")
    <!-- Menu End -->
    
    <div id="container">
        <div class="ContainerBG">

            @Html.Partial("_LeftMenuPartial")

            @RenderBody()
        </div>
    </div>

    <footer role="contentinfo"><div class="Width1200"><div class="Copyright">GPing&copy;2017</div></div></footer>
</body>
</html>

ECTable.Admin/Views/Shared/_LeftMenuPartial.cshtml
@{
    var currentController = ViewContext.RouteData.Values["controller"].ToString().Trim();
    var currentAction = ViewContext.RouteData.Values["action"].ToString().Trim();
}

@if (currentController == "Product")
{
<aside role="complementary">
    <h2>商品管理</h2>
    <div class="sidebarMenu">
        <ul>
            <li><a href="@Url.Action("ProductList", "Product", new { FunctionMode = "NewProduct" })">新增/異動商品清單</a></li>
            <li><a href="@Url.Action("ProductClassList", "Product")">商品類別管理</a></li>
            <li><a href="@Url.Action("ProductWayList", "Product")">烹調方式管理</a></li>
            <li><a href="@Url.Action("ProductList", "Product", new { FunctionMode = "Product" })">商品清單</a></li>
        </ul>
    </div>
</aside>
}

ECTable.Admin/Views/Shared/_MenuPartial.cshtml
<header role="navigation">
    <div class="Width1200">
        <div class="HeaderRight">
            <div class="NewsPaper"><a href="@Url.Action("Login", "Login")">登出管理後台</a></div>
            <nav role="navigation" class="nav">
                <ul class="navigation">
                    <li class="LiWidth142"><a href="#">訂單管理<br><span style="font-size:80%">Order</span></a></li>
                    <li class="LiWidth142"><a href="#">會員管理<br><span style="font-size:80%">Member</span></a></li>
                    <li class="LiWidth142"><a href="#">折價券管理<br><span style="font-size:80%">Coupons</span></a></li>
                    <li class="LiWidth142"><a href="#">Banner管理<br><span style="font-size:80%">Banner</span></a></li>
                    <li class="LiWidth142"><a href="@Url.Action("ProgramList", "Program")">訂閱計劃管理<br><span style="font-size:80%">Program</span></a></li>
                    <li class="LiWidth142"><a href="@Url.Action("CurationList", "Curation")">策展管理<br><span style="font-size:80%">Curations</span></a></li>
                    <li class="LiWidth142"><a href="@Url.Action("BrandList", "Brand")">品牌管理<br><span style="font-size:80%">Brand</span></a></li>
                    <li class="LiWidth142"><a href="@Url.Action("ProductList", "Product")">商品管理<br><span style="font-size:80%">Product</span></a></li>
                </ul>
            </nav>
        </div>
    </div>
</header>

ECTable.Admin/Views/Shared/_SortingPartial.cshtml
<input type="hidden" name="sortingField" id="sortingField" />
<input type="hidden" name="sortingDirection" id="sortingDirection" />